// --- Camera ---
export const SET_PHOTO_FOR_CITATION = 'SET_PHOTO_FOR_CITATION';

// --- Citation ---
export const SAVE_PHOTO_CITATION = 'SAVE_PHOTO_CITATION';
export const RELEASE_PHOTO_CITATION = 'RELEASE_PHOTO_CITATION';
export const UNDO_PHOTO_CITATION = 'UNDO_PHOTO_CITATION';


export const ADD_LINE_CITATION = 'ADD_LINE_CITATION';
export const UPDATE_LINE_CITATION = 'UPDATE_LINE_CITATION';
export const RELEASE_LINE_CITATION = 'RELEASE_LINE_CITATION';

// --- NoteList ---
export const ADD_NOTE = 'ADD_NOTE';
export const REMOVE_ACTIVE_NOTE = 'REMOVE_ACTIVE_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
export const RELEASE_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
