export const SET_PHOTO_FOR_CITATION = 'SET_PHOTO_FOR_CITATION';
export const STOP_PHOTO_CITATION = 'STOP_PHOTO_CITATION';
export const ADD_NOTE = 'ADD_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const EDIT_NOTE = 'EDIT_NOTE';
