// --- Camera ---
export const SET_PHOTO_FOR_CITATION = 'SET_PHOTO_FOR_CITATION';

// --- Citation ---
export const RELEASE_PHOTO_CITATION = 'RELEASE_PHOTO_CITATION';
export const UNDO_PHOTO_CITATION = 'UNDO_PHOTO_CITATION';

export const ADD_LINE_CITATION = 'ADD_LINE_CITATION';
export const UPDATE_LINE_CITATION = 'UPDATE_LINE_CITATION';
export const RELEASE_LINE_CITATION = 'RELEASE_LINE_CITATION';
export const SET_CITATION_LINE_WIDTH = 'SET_CITATION_LINE_WIDTH';
export const ADD_NEW_NOTE_TO_LIST_START = 'ADD_NEW_NOTE_TO_LIST_START';
export const ADD_NEW_NOTE_TO_LIST_END = 'ADD_NEW_NOTE_TO_LIST_END';

// --- NoteList ---
export const ADD_NEW_NOTE_TO_LIST = 'ADD_NEW_NOTE_TO_LIST';
export const REMOVE_ACTIVE_NOTE = 'REMOVE_ACTIVE_NOTE';
export const REMOVE_NOTE = 'REMOVE_NOTE';
export const UPDATE_ACTIVE_NOTE = 'UPDATE_ACTIVE_NOTE';
export const SET_ACTIVE_NOTE = 'SET_ACTIVE_NOTE';
export const RELEASE_ACTIVE_NOTE = 'RELEASE_ACTIVE_NOTE';

// --- Persist ---
export const PERSIST_REHYDRATE_ACTION_TYPE = 'persist/REHYDRATE';
